version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/requirements/nginx/nginx.conf
      - ./nginx.crt:/requirements/nginx/nginx.crt
      - ./nginx.key:/requirements/nginx/nginx.key
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
