version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx.conf
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
