version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    env_file: .env
    networks:
      - inception
    restart: on-failure
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - ~/data/wordpress:/var/www/html
    ports:
      - 9000:9000
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: on-failure
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - ~/data/wordpress:/var/www/html
    ports:
      - 443:443
    env_file: .env
    depends_on:
      - wordpress
    networks:
      - inception
    restart: on-failure
networks:
  inception:
    driver: bridge
