version: '3'

services:
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx
      - ./requirements/nginx/tools/:/usr/share/nginx/html

networks:
  mynetwork:
    driver: bridge
